### PR TITLE
Added more UTs for util.py for dev branch

### PR DESCRIPTION
**Pull request by marcemq**
New added UTs consider:

- function calls with no arguments for both assert_is_flat_same_shape() and assert_is_positive()

- new UTs for assert_is_positive() function

- based on assert_is_positive() description, a UT with 2D ndarray was included too.

@willieneis @YoungseogChung @IanChar @HanGuo97

Test execution output:
image

### CODE REVIEW

**Comment by marcemq** [comment]
@IanChar is this PR ready to be merged or did I missed something?

**Comment by IanChar** [comment]
Sorry I accepted it before I realized it was for the wrong branch. This will need to be a PR for the dev branch too.

**Comment by IanChar** [comment]
Hi @marcemq, this PR is still targeting uncertainty-toolbox:master (albeit from your branch called dev now). 

image

Note it should say into uncertainty-toolbox:dev

**Comment by IanChar** [comment]
Here is an example of how to do this with the GUI

image

**Comment by marcemq** [comment]
Hello @IanChar.

Thank you for your guidance. I was able to change to `uncertanty-toolbox:dev` 🥳 
I think the changes are ready to be merged now.

**Review by IanChar — APPROVED** [review]

**Comment by IanChar** [comment]
Great thanks for your contribution! We will hopefully merge dev into master soon.

**Pull request merged**
