### PR TITLE
Fixed minor typos.

### PR DESCRIPTION
**Pull request by marcemq**
Signed-off-by: Morales Quispe, Marcela <marcela.morales.quispe@gmail.com>

### CODE REVIEW

**Comment by marcemq** [comment]
Added PR for `master` branch because:
- Changes are typos
- When attempting for `dev` branch, as the guidelines suggest, such branch is three commits behind master and my attempted PR included such commits as if there were part of the proposed changes which is not the case.

**Review by IanChar — APPROVED** [review]

**Comment by IanChar** [comment]
Looks good thank you! Can you instead make a PR for dev branch?

**Comment by marcemq** [comment]
@IanChar I've attempted to follow same steps as I did for #67 but got a warning and I did not wanted to force such push in order to not to mess up with commits history, what should I do? 🤔 

```
➜  uncertainty-toolbox git:(master) git checkout fixed-minor-typos 
Switched to branch 'fixed-minor-typos'                     
➜  uncertainty-toolbox git:(fixed-minor-typos) git push origin fixed-minor-typos:dev 
To https://github.com/marcemq/uncertainty-toolbox.git
 ! [rejected]        fixed-minor-typos -> dev (non-fast-forward)
error: failed to push some refs to 'https://github.com/marcemq/uncertainty-toolbox.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by marcemq** [comment]
@IanChar this is a follow-up for question places in previous comment.

**Comment by IanChar** [comment]
Hey @marcemq sorry for the late reply thanks for following up. Are you sure that you have pulled all changes from the dev branch because there are some more commits there than master?

**Pull request merged**
